package com.example.demon_slayer_lookalike.character

import com.example.demon_slayer_lookalike.R

val demonSlayer = arrayOf(
    Character("카마도 탄지로", R.drawable.tanjiro),
    Character("카마도 네즈코", R.drawable.nezuko),
    Character("아가츠마 젠이츠", R.drawable.zenitsu),
    Character("하시바라 이노스케", R.drawable.inosuke),
    Character("렌고쿠 쿄쥬로", R.drawable.rengoku),
    Character("우즈이 텐겐", R.drawable.tengen),
    Character("칸로지 미츠리", R.drawable.mitsuri),
    Character("히메지마 교메이", R.drawable.gyomei),
    Character("토키토 무이치로", R.drawable.muichiro),
    Character("이구로 오바나이", R.drawable.obanai),
    Character("토미오카 기유", R.drawable.giyu),
    Character("코쵸우 시노부", R.drawable.shinobu),
    Character("시나즈가와 사네미", R.drawable.sanemi),
    Character("코쵸우 카나에", R.drawable.kanae),
    Character("우로코다키 사콘지", R.drawable.urokodaki),
    Character("쿠와지마 지고로", R.drawable.jigoro),
    Character("츠유리 카나오", R.drawable.kanao),
    Character("시나즈가와 겐야", R.drawable.genya),
    Character("칸자키 아오이", R.drawable.aoi),
    Character("카이가쿠", R.drawable.kaigaku),
    Character("무라타", R.drawable.murata),
    Character("우부야시키 카가야", R.drawable.kagaya),
    Character("하가네즈카 호타루", R.drawable.hotaru),
    Character("키부츠지 무잔", R.drawable.muzan),
    Character("스사마루", R.drawable.susamaru),
    Character("야하바", R.drawable.susamaru),
    Character("루이", R.drawable.rui),
    Character("코쿠시보", R.drawable.kokushibou),
    Character("아카자", R.drawable.akaza),
    Character("도우마", R.drawable.douma),
    Character("굣코", R.drawable.gyokko),
    Character("다키", R.drawable.daki),
    Character("한텐구", R.drawable.hantengu),
    Character("나키메", R.drawable.nakime),
    Character("쿄우가이", R.drawable.kyogai),
    Character("엔무", R.drawable.enmu),
    Character("타마요", R.drawable.tamayo),
    Character("유시로", R.drawable.yushiro),
    Character("규타로", R.drawable.gyutaro)
)